### ISSUE TITLE
hv_crate merge to main checklist

### ISSUE THREAD

**Issue by ethteck** [ethteck/bdiff#56]
- [x] send theme to hex_view
- [x] lock scroll pos not working
- [x] diffing not working
